import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import crypto from 'node:crypto';
import { W645_DOMAIN_BOARD_SCHEMA, W645_KILL_SWITCH_RECEIPT_SCHEMA, W645_REQUIRED_DOMAINS, W645_KILL_SWITCHES, validateW645ProductionEvidenceContract } from '../../config/w645-production-evidence-contract.mjs';
import { validateW645DomainBoard, validateW645KillSwitchReceipt, validateW645W638Index } from '../../scripts/lib/w645-production-evidence.mjs';
const H='a'.repeat(64), C='b'.repeat(40); const digest=(b)=>crypto.createHash('sha256').update(b).digest('hex');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'w645-')); fs.mkdirSync(path.join(root,'evidence/w638'),{recursive:true}); fs.mkdirSync(path.join(root,'evidence/w645/artifacts'),{recursive:true}); fs.writeFileSync(path.join(root,'evidence/w638/proof.json'),'{}'); fs.writeFileSync(path.join(root,'evidence/w645/artifacts/proof.json'),'{}'); return root;}
const candidate={candidateDigest:H,commitSha:C,w639FreezeDigest:H,distPayloadDigest:H}; const preview={deploymentId:'preview-123'};
function index(root){const rel='evidence/w638/proof.json',buf=fs.readFileSync(path.join(root,rel)); const lanes=['billing','referral','local-creator','direct-provider','companion'].map(id=>({id,status:'pass',requirements:[]})); const artifacts=[{path:rel,bytes:buf.length,sha256:digest(buf)}]; const value={schema:'eonapp.production-evidence-index.w638.v1',wave:'W638',sourceGateOk:true,lanes,artifacts,boundaries:{syntheticCanCertify:false,sourceCanCertify:false,secretsIncluded:false}}; value.indexDigest=digest(Buffer.from(JSON.stringify({lanes,artifacts}),'utf8')); return value;}
function domains(root){const rel='evidence/w645/artifacts/proof.json',buf=fs.readFileSync(path.join(root,rel)); return {schema:W645_DOMAIN_BOARD_SCHEMA,wave:'W645',candidateDigest:H,previewDeploymentId:'preview-123',occurredAt:'2026-07-11T12:00:00.000Z',ownerReviewed:true,redactionReviewed:true,secretsIncluded:false,directIdentifiersIncluded:false,absolutePathsIncluded:false,domains:W645_REQUIRED_DOMAINS.map(id=>({id,status:'pass',mode:id==='city'?'active-owner-certified':id==='creator'?'image-active-video-gated':id==='referral'?'gated-truthful':'active',candidateDigest:H,previewDeploymentId:'preview-123',ownerReviewed:true,redactionReviewed:true,artifacts:[{path:rel,bytes:buf.length,sha256:digest(buf)}]}))};}
const laneDecisions={referral:{decision:'gated'},'direct-provider':{decision:'gated'},companion:{decision:'gated'}};
const creator={launchScopePass:true,fullVideoCertified:false}; const city={ok:true,overallScore:9.6,minimumCategoryScore:9.2};
test('contract freezes exact-candidate evidence and non-destructive recovery',()=>assert.equal(validateW645ProductionEvidenceContract().ok,true));
test('W638 index digest and artifacts are reverified',()=>{const root=fixture(); assert.equal(validateW645W638Index(index(root),{root}).ok,true); const bad=index(root); bad.indexDigest=H; assert.equal(validateW645W638Index(bad,{root}).ok,false);});
test('all eleven domains require real artifacts and exact candidate linkage',()=>{const root=fixture(); assert.equal(validateW645DomainBoard(domains(root),{root,candidate,preview,laneDecisions,creator,city}).ok,true); const bad=domains(root); bad.domains[0].artifacts=[]; assert.equal(validateW645DomainBoard(bad,{root,candidate,preview,laneDecisions,creator,city}).ok,false);});
test('gated referral must be labelled truthfully',()=>{const root=fixture(); const bad=domains(root); bad.domains.find(x=>x.id==='referral').mode='active'; assert.equal(validateW645DomainBoard(bad,{root,candidate,preview,laneDecisions,creator,city}).ok,false);});
test('kill switches must preserve data and create no customer mutation',()=>{const receipt={schema:W645_KILL_SWITCH_RECEIPT_SCHEMA,wave:'W645',status:'pass',occurredAt:'2026-07-11T12:00:00.000Z',candidateDigest:H,previewDeploymentId:'preview-123',rollbackDeploymentId:'prod-previous',switches:W645_KILL_SWITCHES.map(x=>({id:x.id,setting:x.setting,safeValue:x.safeValue,previewRehearsed:true,expectedEffectObserved:true,dataPreserved:true,customerMutationCreated:false})),d1ResetPerformed:false,migrationRollbackPerformed:false,ownerReviewed:true,redactionReviewed:true,secretsIncluded:false}; assert.equal(validateW645KillSwitchReceipt(receipt,{candidate,preview}).ok,true); receipt.switches[0].dataPreserved=false; assert.equal(validateW645KillSwitchReceipt(receipt,{candidate,preview}).ok,false);});
