import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { EON_CITY_W697_VISUAL_IDENTITIES, buildEonCityW697BuildingVariant, getEonCityW697DistrictVisualIdentity, validateEonCityW697DistrictVisualIdentities, getEonCityW697DistrictVisualIdentityTruth } from '../../assets/js/city/w697/eon-city-w697-district-visual-identity.js';
import { inspectW697DistrictVisualIdentity } from '../../scripts/w697-district-visual-identity-gate.mjs';

test('W697 gives all nine districts unique visual fingerprints',()=>{ const r=validateEonCityW697DistrictVisualIdentities(); assert.equal(r.ok,true,r.errors.join('|')); assert.equal(r.identityCount,9); assert.equal(r.uniqueFingerprints,9); assert.ok(r.uniqueBuildingGrammars>=8); });
test('W697 preserves stable IDs while differentiating key district grammars',()=>{ assert.equal(getEonCityW697DistrictVisualIdentity('creator-atrium').buildingGrammar,'terrace'); assert.equal(getEonCityW697DistrictVisualIdentity('forge-basilica').buildingGrammar,'cathedral'); assert.equal(getEonCityW697DistrictVisualIdentity('archive-canopy').buildingGrammar,'canopy'); assert.equal(getEonCityW697DistrictVisualIdentity('vault-station').buildingGrammar,'vault'); assert.equal(getEonCityW697DistrictVisualIdentity('trade-dome').buildingGrammar,'civic-dome'); });
test('W697 deterministic variants retain district fingerprint',()=>{ const a=buildEonCityW697BuildingVariant('creator-atrium',2); const b=buildEonCityW697BuildingVariant('creator-atrium',2); assert.deepEqual(a,b); assert.equal(a.fingerprint,EON_CITY_W697_VISUAL_IDENTITIES['creator-atrium'].fingerprint); });
test('W697 active renderer contains distinct shape paths without another renderer',()=>{ const src=fs.readFileSync(new URL('../../assets/js/city/w690/eon-city-w690-district-belts-babylon.js',import.meta.url),'utf8'); for(const token of ["'terrace'","'cathedral'","'citadel'","'canopy'","'vault'","'civic-dome'","'amphitheatre'","'concourse'"]) assert.match(src,new RegExp(token.replace(/[-/\\^$*+?.()|[\]{}]/g,'\\$&'))); assert.match(src,/oneCanonicalScene: true/); assert.match(src,/secondRenderLoopCreated: false/); });
test('W697 truth and focused gate remain bounded',()=>{ const truth=getEonCityW697DistrictVisualIdentityTruth(); assert.equal(truth.functionalArchitectureDominatesDecoration,true); assert.equal(truth.genericRingsSubordinate,true); assert.equal(truth.automaticExecution,false); const r=inspectW697DistrictVisualIdentity(); assert.equal(r.ok,true,r.checks.filter(x=>!x.pass).map(x=>x.id).join(',')); });
