import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
import{projectEonNexusW699CommandClarity,resolveEonNexusW699GestureStatus,validateEonNexusW699CommandClarity,getEonNexusW699CommandClarityTruth}from'../../assets/js/nexus/w699/eon-nexus-w699-command-clarity.js';import{inspectW699NexusCommandClarity}from'../../scripts/w699-nexus-command-clarity-gate.mjs';
const model={atlasAvailable:true,conversationRoute:'/chat',commandField:{selectedObject:{id:'approval:1',kind:'approval',label:'Launch approval',status:'waiting',action:'review'},selectedPrimaryVerb:{label:'Review approval',action:'review'}}};
test('W699 limits persistent product actions to three',()=>{const p=projectEonNexusW699CommandClarity(model,{selectedObjectIds:['approval:1'],compareIds:[]},{spatialAvailable:true});const r=validateEonNexusW699CommandClarity(p);assert.equal(r.ok,true,r.errors.join('|'));assert.deepEqual(p.persistentActions.map(x=>x.id),['primary','atlas','more']);assert.equal(p.persistentActionCount,3);});
test('W699 explains City placement before explicit entry',()=>{const p=projectEonNexusW699CommandClarity(model,{}, {spatialAvailable:true});assert.equal(p.city.districtId,'command-centre');assert.match(p.city.reason,/Approvals belong/);assert.equal(p.city.reviewRequired,true);assert.equal(p.automaticNavigation,false);});
test('W699 compare and group states are explicit',()=>{const one=projectEonNexusW699CommandClarity(model,{selectedObjectIds:['a'],compareIds:['a']},{});assert.match(one.compare.instruction,/one more/);assert.equal(one.group.ready,false);const two=projectEonNexusW699CommandClarity(model,{selectedObjectIds:['a','b'],compareIds:['a','b']},{});assert.equal(two.compare.ready,true);assert.equal(two.group.ready,true);});
test('W699 exposes off, available, active and unavailable gesture states',()=>{assert.equal(resolveEonNexusW699GestureStatus({detectorAvailable:false}).status,'off');assert.equal(resolveEonNexusW699GestureStatus({detectorAvailable:true}).status,'available');assert.equal(resolveEonNexusW699GestureStatus({interactionState:{gestureMode:'active'},detectorAvailable:true}).status,'active');assert.equal(resolveEonNexusW699GestureStatus({interactionState:{gestureMode:'unavailable'}}).status,'unavailable');});
test('W699 active UI has More and Stop Camera while preserving normal controls',()=>{const src=fs.readFileSync(new URL('../../assets/js/nexus/eon-nexus-live.js',import.meta.url),'utf8');assert.match(src,/const moreCommand/);assert.match(src,/const stopCameraButton/);assert.match(src,/Mouse, touch, keyboard/);});
test('W699 truth and focused gate remain non-executing',()=>{const t=getEonNexusW699CommandClarityTruth();assert.equal(t.threePersistentActions,true);assert.equal(t.cameraStartsAutomatically,false);assert.equal(t.automaticNavigation,false);assert.equal(t.startsWork,false);const r=inspectW699NexusCommandClarity();assert.equal(r.ok,true,r.checks.filter(x=>!x.pass).map(x=>x.id).join(','));});
